FROM mariadb:latest

RUN apt-get update
#RUN apt-get install -y cron
#RUN apt-get install -y systemctl
#RUN apt-get install -y nano
#RUN systemctl enable cron

COPY ./db-script/db-backup.sh /usr/db-script/db-backup.sh
RUN chmod +x /usr/db-script/db-backup.sh