FROM ubuntu:latest

RUN apt-get update
RUN apt install iputils-ping -y
RUN apt-get install python3 -y
RUN apt-get -y install python3-pip
#RUN apt-get install -y mariadb-backup

WORKDIR /usr/app/src

COPY ./requirements.txt ./
RUN pip install -r requirements.txt

# ENTRYPOINT ["tail"]
# CMD ["-f","/dev/null"]
